"""
Byte-Level Constrained Finite State Machine (FSM) Decoding for ByT5 ACOS
=======================================================================
Implements ACOSByteFSM as a Hugging Face LogitsProcessor to strictly constrain
autoregressive decoding for ByT5 models (vocabulary size 256 + special tokens):
  1. Guarantees valid quadruple formatting: [ aspect | category | sentiment | opinion ] ; ...
  2. Guarantees 0% category hallucinations by restricting category slot to the 22 valid INSA categories.
  3. Guarantees valid sentiment polarity (POSITIVE, NEGATIVE, NEUTRAL).
  4. Enforces valid delimiter tokens and transitions between slots.
"""
import logging

try:
    import torch
    from transformers import LogitsProcessor
except ImportError:
    torch = None
    LogitsProcessor = object

from linearization import CATEGORIES, SENTIMENTS

logger = logging.getLogger(__name__)


class ByteTrieNode:
    def __init__(self):
        self.children: dict[int, ByteTrieNode] = {}
        self.is_terminal: bool = False


class ByteTrie:
    """Prefix trie operating on sequences of raw byte token IDs."""

    def __init__(self):
        self.root = ByteTrieNode()

    def insert(self, token_ids: list[int]):
        curr = self.root
        for tid in token_ids:
            if tid not in curr.children:
                curr.children[tid] = ByteTrieNode()
            curr = curr.children[tid]
        curr.is_terminal = True

    def get_valid_continuations(self, prefix_ids: list[int]) -> tuple[set[int], bool]:
        """
        Traverses trie with prefix_ids.
        Returns:
            (valid_next_token_ids, is_terminal_matching_point)
        """
        curr = self.root
        for tid in prefix_ids:
            if tid not in curr.children:
                return set(), False
            curr = curr.children[tid]
        valid_next = set(curr.children.keys())
        return valid_next, curr.is_terminal


class ACOSByteFSM(LogitsProcessor):
    """
    LogitsProcessor enforcing a regular grammar over ByT5 generated byte sequences.
    
    Grammar:
      Target   := "None" | Quad ( " ; " Quad )*
      Quad     := "[ " Aspect " | " Category " | " Sentiment " | " Opinion " ]"
      Category := 1 of 22 INSA taxonomy categories
      Sentiment:= POSITIVE | NEGATIVE | NEUTRAL
    """

    def __init__(self, tokenizer, categories: set[str] = CATEGORIES, sentiments: set[str] = SENTIMENTS):
        self.tokenizer = tokenizer
        self.eos_token_id = tokenizer.eos_token_id
        self.pad_token_id = tokenizer.pad_token_id

        # Encode structural string fragments into exact token ID sequences
        def enc(s: str) -> list[int]:
            return tokenizer.encode(s, add_special_tokens=False)

        self.bracket_open_ids = enc("[ ")
        self.bracket_close_ids = enc(" ]")
        self.pipe_sep_ids = enc(" | ")
        self.semi_sep_ids = enc(" ; ")
        self.none_ids = enc("None")
        self.null_ids = enc("NULL")

        # Byte IDs for initial bracket / None
        self.initial_allowed_ids = {self.bracket_open_ids[0], self.none_ids[0]}

        # Pre-build Tries for Category and Sentiment
        self.category_trie = ByteTrie()
        for cat in categories:
            self.category_trie.insert(enc(cat))

        self.sentiment_trie = ByteTrie()
        for sent in sentiments:
            self.sentiment_trie.insert(enc(sent))

    def _get_allowed_tokens_for_sequence(self, token_ids: list[int]) -> set[int]:
        """
        Given the sequence generated so far (token_ids), determine which token IDs
        are legally permitted at the next generation step.
        """
        # Strip leading decoder start / pad token if present
        clean_ids = [t for t in token_ids if t != self.pad_token_id]

        # Step 0: Empty sequence
        if not clean_ids:
            return set(self.initial_allowed_ids)

        # Decode generated text so far
        text = self.tokenizer.decode(clean_ids, skip_special_tokens=True)

        # Case A: Sequence is emitting "None"
        if text.startswith("None") or "None".startswith(text):
            if text == "None":
                return {self.eos_token_id}
            # Continue typing "None"
            next_idx = len(text)
            target = "None"
            if next_idx < len(target):
                next_char = target[next_idx]
                return set(self.tokenizer.encode(next_char, add_special_tokens=False))
            return {self.eos_token_id}

        # Case B: Standard quadruple sequence
        # Check if we are between quads (after a closing bracket " ]")
        # Find position of last opening bracket "["
        last_bracket_idx = text.rfind("[")
        if last_bracket_idx == -1:
            # Haven't opened bracket yet
            return {self.bracket_open_ids[0]}

        # Text inside the currently open quad
        curr_quad_text = text[last_bracket_idx:]

        # Check if the current quad was closed with " ]"
        if curr_quad_text.endswith(" ]"):
            # Can either finish (EOS) or continue with semicolon delimiter " ; ["
            semi_first = self.semi_sep_ids[0]
            return {self.eos_token_id, semi_first}

        # If we are in the middle of semicolon continuation " ; ["
        if text.endswith((" ;", " ; ")):
            if text.endswith(" ; "):
                return {self.bracket_open_ids[0]}
            return set(self.tokenizer.encode(" ", add_special_tokens=False))

        # If just started a quad "[ "
        if curr_quad_text in ("[", "[ "):
            if curr_quad_text == "[":
                return set(self.tokenizer.encode(" ", add_special_tokens=False))
            # First char of Aspect (can be any Amharic byte or 'N' for NULL)
            # Cannot be pipe delimiter immediately unless empty aspect
            return set(range(3, 259))

        # We are inside a quad. Count pipe delimiters to find active slot:
        # "[ <aspect> | <category> | <sentiment> | <opinion>"
        parts = curr_quad_text.split(" | ")
        num_pipes = len(parts) - 1

        # Slot 1: Aspect (num_pipes == 0)
        if num_pipes == 0:
            # Model is generating Aspect span
            # Allowed: any valid byte, OR can start the pipe delimiter " | "
            # Delimiter begins with space
            space_id = self.tokenizer.encode(" ", add_special_tokens=False)[0]
            allowed = set(range(3, 259))
            allowed.add(space_id)
            return allowed

        # Slot 2: Category (num_pipes == 1)
        elif num_pipes == 1:
            cat_prefix = parts[1]
            cat_prefix_ids = self.tokenizer.encode(cat_prefix, add_special_tokens=False) if cat_prefix else []
            valid_next, is_terminal = self.category_trie.get_valid_continuations(cat_prefix_ids)
            allowed = set(valid_next)

            # If category is complete, allow starting the next delimiter " | "
            if is_terminal:
                space_id = self.tokenizer.encode(" ", add_special_tokens=False)[0]
                allowed.add(space_id)

            if not allowed:
                # Fallback to space delimiter if matched
                allowed = {self.tokenizer.encode(" ", add_special_tokens=False)[0]}
            return allowed

        # Slot 3: Sentiment (num_pipes == 2)
        elif num_pipes == 2:
            sent_prefix = parts[2]
            sent_prefix_ids = self.tokenizer.encode(sent_prefix, add_special_tokens=False) if sent_prefix else []
            valid_next, is_terminal = self.sentiment_trie.get_valid_continuations(sent_prefix_ids)
            allowed = set(valid_next)

            # If sentiment is complete, allow starting the next delimiter " | "
            if is_terminal:
                space_id = self.tokenizer.encode(" ", add_special_tokens=False)[0]
                allowed.add(space_id)

            if not allowed:
                allowed = {self.tokenizer.encode(" ", add_special_tokens=False)[0]}
            return allowed

        # Slot 4: Opinion (num_pipes == 3)
        elif num_pipes == 3:
            # Generating Opinion span
            # Allowed: any valid byte, OR can close the quad with " ]"
            space_id = self.tokenizer.encode(" ", add_special_tokens=False)[0]
            bracket_close_id = self.tokenizer.encode("]", add_special_tokens=False)[0]
            allowed = set(range(3, 259))
            allowed.add(space_id)
            allowed.add(bracket_close_id)
            return allowed

        # Default fallback: allow EOS or any byte to avoid deadlocks
        return {self.eos_token_id} | set(range(3, 259))

    def __call__(self, input_ids: torch.LongTensor, scores: torch.FloatTensor) -> torch.FloatTensor:
        """
        Masks out disallowed token IDs at each generation step across the batch.
        """
        batch_size = input_ids.shape[0]

        for b in range(batch_size):
            seq = input_ids[b].tolist()
            try:
                allowed = self._get_allowed_tokens_for_sequence(seq)
                if allowed:
                    # Create negative mask
                    mask = torch.full((scores.size(-1),), float("-inf"), dtype=scores.dtype, device=scores.device)
                    valid_indices = [idx for idx in allowed if 0 <= idx < scores.size(-1)]
                    if valid_indices:
                        mask[valid_indices] = 0.0
                        scores[b] = scores[b] + mask
            except (IndexError, KeyError, ValueError) as err:
                logger.debug("ACOSByteFSM constraint fallback on sequence: %s", err)

        return scores
